server:
  port:
    9501
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
spring:
  application:
    name: eobao-onboarding-app
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect